### ISSUE TITLE
Load nodeset files from UACloudLibrary

### ISSUE THREAD

**Issue by eoursel** [digitaltwinconsortium/UA-CloudNodesetViewer#1]
Hi @barnstee 

Good work. 

Just an idea, Could it be possible to load nodeset files from the UACloudLibrary?  I have seen it is possible to push a nodeset to the cloud library but not fetching a nodeset from the library. 

2 possible things options;  

1. Load a model from the Library instead of loading it from the local filesystem. 
2. Load dependent models when loading a model. For instance in the case of the models which are dependent of the DI automatically load the DI from the UA Cloud Library. 

Nice weekend

**Comment by barnstee** [comment]
Thanks Eric. This was actually on my mind for a long time, too, but I didn't have time so far. I'll take a stab at it next week since now I have a bit more time since the UA Cloud Library was successfully released!

**Comment by barnstee** [comment]
Implemented with checkin https://github.com/digitaltwinconsortium/UANodesetWebViewer/commit/ff19caf539055a1801dab1e1bf61b13410e4c430
