### ISSUE TITLE
VariableRead in BrowserController.cs does not return proper Content if value is null but read succeeded.

### ISSUE THREAD

**Issue by muenchris** [digitaltwinconsortium/UA-CloudNodesetViewer#10]
There are nodesets that have UAObjects with variables without a default value. The Read of these variables succeeds but value is null and the StatusCode might be "BadWaitingForInitialData". 
In Line 848 if BrowserController.cs a "Content" is only rendered if the variable has not null value. This prevents the "write" dialog from showing properly.

Suggestion: add an actionResult for the else branch as well

**Comment by barnstee** [comment]
Fixed with https://github.com/digitaltwinconsortium/UANodesetWebViewer/commit/cc3030c2282e9244ce875c26408c38c2cd8a7f1f
