### ISSUE TITLE
Writing of a non-string Variable fails 

### ISSUE THREAD

**Issue by muenchris** [digitaltwinconsortium/UA-CloudNodesetViewer#11]
I get a nullpointerexception in "session.read" at line 233 of OpcSessionHelper.cs if I try to write to a "float" variable.
Strings work fine.

This could be related to the BadWaitingForInitialData issue

**Comment by barnstee** [comment]
Writing of variables should not have been supported as the server created is only created for browsing/reading. I have "fixed" this by removing the write/method call code paths with https://github.com/digitaltwinconsortium/UANodesetWebViewer/commit/8cd9ebcf7972ba879349732bc2ec08af41ba8fe2
