### ISSUE TITLE
Issue with generated AAS

### ISSUE THREAD

**Issue by eoursel** [digitaltwinconsortium/UA-CloudNodesetViewer#12]
Hi @barnstee 

When generating an AAS from an information model opened from the cloud library. 

It seems that Aasx Package Explorer is not able to open the XML file  embedded as a submodel. 

Is it a problem with the generated AAS or with AASX Packager Explorer? 

Find below an abstract of the trace of AASX Package Explorer. 

`Error: When displaying content /aasx//app/NodeSets/nodeset2.xml, an error occurred: Le composant spécifié n'existe pas dans le package. Le composant spécifié n'existe pas dans le package. at    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158.
    Stacktrace:    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158
Trying display content /aasx//app/NodeSets/nodeset2.xml ..
Error: When displaying content /aasx//app/NodeSets/nodeset2.xml, an error occurred: Le composant spécifié n'existe pas dans le package. Le composant spécifié n'existe pas dans le package. at    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158.
    Stacktrace:    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158
Trying display content /aasx//app/NodeSets/nodeset2.xml ..
Error: When displaying content /aasx//app/NodeSets/nodeset2.xml, an error occurred: Le composant spécifié n'existe pas dans le package. Le composant spécifié n'existe pas dans le package. at    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158.
    Stacktrace:    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158
Trying display content /aasx//app/NodeSets/nodeset2.xml ..
Error: When displaying content /aasx//app/NodeSets/nodeset2.xml, an error occurred: Le composant spécifié n'existe pas dans le package. Le composant spécifié n'existe pas dans le package. at    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158.
    Stacktrace:    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158
Trying display content /aasx//app/NodeSets/nodeset2.xml ..
Error: When displaying content /aasx//app/NodeSets/nodeset2.xml, an error occurred: Le composant spécifié n'existe pas dans le package. Le composant spécifié n'existe pas dans le package. at    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158.
    Stacktrace:    à System.IO.Packaging.Package.GetPart(Uri partUri)
   à AdminShellNS.AdminShellPackageEnv.GetLocalStreamFromPackage(String uriString, FileMode mode) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1044
   à AdminShellNS.AdminShellPackageEnv.MakePackageFileAvailableAsTempFile(String packageUri, Boolean keepFilename) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:ligne 1335
   à AasxPackageExplorer.MainWindow.ShowContent_Click(Object sender, RoutedEventArgs e) dans D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:ligne 2158
`

Regards

**Comment by barnstee** [comment]
Yeah, there were several breaking changes introduced in Package Explorer, it is a moving target. I will see if I can make it work again next week...

**Comment by barnstee** [comment]
I managed to reproduce the error and fix it with commit https://github.com/digitaltwinconsortium/UANodesetWebViewer/commit/81e58c27730ad626d95420c7f7fe753cef705474

**Comment by barnstee** [comment]
Please try it out with the latest package and close the issue if it is fixed.

**Comment by eoursel** [comment]
Thanks Erich I will test it. Do you plan to write a submodel template to host Opcua information models into a standardized submodel? By exposing the Metadata that is in the cloud library as properties?

**Comment by barnstee** [comment]
Yes, the IDTA is already working on it.

**Comment by barnstee** [comment]
Is it working?

**Comment by eoursel** [comment]
@barnstee I remember I made a quick test before my vacations. It was not working unfortunately, albeit not sure if it is the same error. I will retest probably before the end of the week or this weekend to be sure.

Thanks Erich.

**Comment by barnstee** [comment]
Did you try this out and is it working now?

**Comment by eoursel** [comment]
yes working with version v2022-05-10 of the AASX explorer. Thanks @barnstee
