### ISSUE TITLE
Error loading some nodesets

### ISSUE THREAD

**Issue by eoursel** [digitaltwinconsortium/UA-CloudNodesetViewer#14]
Hi @barnstee 

i deployed the APP on a Azure APP with visual studio with my Azure subscription. 

When i try to open some NodeSets (for instance machinery, or robotics) there is just an Error box  and the only thing to do is to reset the application since it's not possible to login again. I have the same behavior on a docker box local machine running on my personal NAS.  

Best regards

**Comment by barnstee** [comment]
Can you check the app logs and send it to me?

**Comment by eoursel** [comment]
Hi @barnstee  

When started as a docker container locally or on azure there is an error when loading the certificate at server starting. Of course i don't have the problem if i start the app from my windows machine directly from Visual Studio. 

[error_nodesetwebviewer.log](https://github.com/digitaltwinconsortium/UANodesetWebViewer/files/9192685/error_nodesetwebviewer.log)

Regards

**Comment by barnstee** [comment]
From the logs: "Opc.Ua.ServiceResultException: The certificate with subject CN=UA NodeSet Web Viewer in the configuration is invalid.  Please update or delete the certificate from this location:  CurrentUser\\My". So it looks like the Registry cert store location is not working in your Docker environment. I have just switched this over to use a local directory instead. Please download the latest Docker image and try again.

**Comment by eoursel** [comment]
Yes it works with the last version of the container. Running on a QNAP NAS appliance.  Not tried yet a deployment on Azure but it should solve the problem also.  Thanks @barnstee
