### ISSUE TITLE
Loading models dependent from the DI is not working

### ISSUE THREAD

**Issue by eoursel** [digitaltwinconsortium/UA-CloudNodesetViewer#4]
Hi @barnstee 

Tried to load the MACHINERY model dependent from the DI directly from **Open nodeset files from UA Cloud Library**

There is an exception due the fact that the DI model is not automatically loaded

> Exception has occurred: CLR/System.Exception
> Une exception de type 'System.Exception' s'est produite dans UANodesetWebViewer.dll mais n'a pas été gérée dans le code utilisateur: 'Importing node ns=2;i=1011 (IMachineTagNameplateType) failed with error: A valid supertype identifier is required.'
>    à UANodesetWebViewer.SimpleNodeManager.ImportNodeset2Xml(IDictionary`2 externalReferences, String resourcepath) dans /mnt/EricPro/dev/code/OPCFoundation/DigitalTwinConsortium/UANodesetWebViewer/Applications/SimpleNodeManager.cs :ligne 132
>    à UANodesetWebViewer.SimpleNodeManager.CreateAddressSpace(IDictionary`2 externalReferences) dans /mnt/EricPro/dev/code/OPCFoundation/DigitalTwinConsortium/UANodesetWebViewer/Applications/SimpleNodeManager.cs :ligne 58
>    à Opc.Ua.Server.MasterNodeManager.Startup()

**Comment by eoursel** [comment]
Small investigation... Really strange. It seems that the DI is in the dictionary but if you load the DI it is not the DI but the ADI. And by the way i can't find the ADI in the dictionary. I am afraid there is something wrong in the UA Cloud Library database. 

![image](https://user-images.githubusercontent.com/6437134/143930690-a9bcff9c-6302-45db-baa0-0bfa2d452454.png)


![image](https://user-images.githubusercontent.com/6437134/143930219-9ae44c0e-469c-437d-b1d5-3c71e7ac8642.png)

**Comment by barnstee** [comment]
Thanks for finding this. That was an upload issue, I accidentally uploaded the wrong nodeset (ADI vs. DI). I've since fixed this!
