### ISSUE TITLE
GetDtkDataType exception thrown way too often

### ISSUE THREAD

**Issue by muenchris** [digitaltwinconsortium/UA-CloudNodesetViewer#9]
This exception slows down the load of a nodeset dramatically - especially in the debugger. Better way:

`
        private static string GetDtdlDataType(string id)
        {
            try
            {
                if (_map.TryGetValue(id, out var ttype))
                    return ttype;
                else
                    return "string";
            }
            catch
            {
                return "string"; // default to string
            }
        }
`

**Comment by barnstee** [comment]
Fixed in https://github.com/digitaltwinconsortium/UANodesetWebViewer/commit/171a68cd3a5b70e66d2926139a536557ddc43338
